name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the file
        run: |
          cd /home/runner/work/sip-hass-card/sip-hass-card/
          npm ci
          npm run build
      - name: Upload files to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/sip-hass-card/sip-hass-card/dist/*.js
          asset_name: ""
          tag: ${{ github.ref }}
          overwrite: true
